export {
    defaultRoles,
    defaultRoleTimings,
    defaultFactionNames,
    defaultNightWakeRules,
} from './data/default-role-definitions'

export const defaultEffects: { [key: string]: Effect } = {
    verliebt: { name: "Verliebt", icon: "fa-heart", duration: "permanent" },
    werwolfziel: { name: "Werwolf-Ziel", icon: "fa-flag", duration: "night" },
    schutznacht: { name: "Geschützt (Nacht)", icon: "fa-shield", duration: "night" },
    geschuetzttag: { name: "Geschützt (Tag)", icon: "fa-shield", duration: "next_day" },
    schlaeftwoanders: { name: "Schläft woanders", icon: "fa-chair", duration: "night" },
    stummnaechstertag: { name: "Darf morgen nicht reden", icon: "fa-comment", duration: "next_day" },
    blockiertnacht: { name: "Blockiert (Nacht)", icon: "fa-lock", duration: "night" },
    ueberprueft: { name: "Überprüft", icon: "fa-eye", duration: "night" },
    beobachtet: { name: "Beobachtet", icon: "fa-glasses", duration: "night" },
    markiertnacht: { name: "Markiert (Nacht)", icon: "fa-flag-checkered", duration: "night" },
    einsamerwolfziel: { name: "Ziel des einsamen Werwolfs", icon: "fa-cross", duration: "night" },
    verwandelt: { name: "Verwandelt", icon: "fa-atom", duration: "permanent" },
    verflucht: { name: "Verflucht", icon: "fa-moon", duration: "permanent" },
    gesegnet: { name: "Gesegnet", icon: "fa-cross", duration: "permanent" },
    vergiftet: { name: "Vergiftet", icon: "fa-vial", duration: "permanent" },
    gebissen: { name: "Gebissen", icon: "fa-vial", duration: "next_day" },
    faehigkeitverbraucht: { name: "Fähigkeit verbraucht", icon: "fa-hourglass-half", duration: "permanent" },
}

export const availableIcons = [
    "fa-image",
    "fa-bell",
    "fa-comment",
    "fa-star",
    "fa-heart",
    "fa-eye",
    "fa-eye-slash",
    "fa-comments",
    "fa-compass",
    "fa-handshake",
    "fa-snowflake",
    "fa-sun",
    "fa-clock",
    "fa-flag",
    "fa-flag-checkered",
    "fa-hand-point-up",
    "fa-moon",
    "fa-lightbulb",
    "fa-map",
    "fa-life-ring",
    "fa-hourglass-half",
    "fa-gem",
    "fa-smile",
    "fa-surprise",
    "fa-sad-cry",
    "fa-meh",
    "fa-kiss-wink-heart",
    "fa-grin-stars",
    "fa-grin-hearts",
    "fa-frown",
    "fa-flushed",
    "fa-dizzy",
    "fa-angry",
    "fa-plane",
    "fa-car",
    "fa-rocket",
    "fa-ship",
    "fa-bicycle",
    "fa-key",
    "fa-fire",
    "fa-tree",
    "fa-leaf",
    "fa-cloud",
    "fa-water",
    "fa-magnet",
    "fa-gears",
    "fa-flask",
    "fa-ticket",
    "fa-palette",
    "fa-feather",
    "fa-pen",
    "fa-anchor",
    "fa-atom",
    "fa-sign",
    "fa-cross",
    "fa-question",
    "fa-shield",
    "fa-wrench",
    "fa-hammer",
    "fa-robot",
    "fa-crown",
    "fa-box",
    "fa-chair",
    "fa-joint",
    "fa-ruler",
    "fa-scroll",
    "fa-coins",
    "fa-puzzle-piece",
    "fa-dice",
    "fa-lock",
    "fa-unlock",
    "fa-glasses",
    "fa-cookie-bite",
    "fa-wine-glass",
    "fa-vial",
    "fa-umbrella"
]
