import { defaultEffects, defaultEffectOrder } from './data/default-effect-definitions'

export {
    defaultRoles,
    defaultRoleTimings,
    defaultFactionNames,
    defaultNightWakeRules,
} from './data/default-role-definitions'

export { defaultEffects, defaultEffectOrder }

export const defaultFeatureFlags: AppFeatureFlags = {
    confirmDialogs: false,
    narratorAssistant: true,
    persistentPlayerNames: true,
    prioritizeStatusEffects: true,
}

const defaultEffectIcons = Array.from(new Set(Object.values(defaultEffects).map((effect) => effect.icon)))

export const availableIcons = Array.from(new Set([
    ...defaultEffectIcons,
    "fa-moon",
    "fa-cloud-moon",
    "fa-paw",
    "fa-bone",
    "fa-teeth",
    "fa-skull",
    "fa-skull-crossbones",
    "fa-ghost",
    "fa-spider",
    "fa-crow",
    "fa-dungeon",
    "fa-mask",
    "fa-user-secret",
    "fa-fingerprint",
    "fa-crosshairs",
    "fa-biohazard",
    "fa-vial",
    "fa-syringe",
    "fa-heart",
    "fa-eye",
    "fa-eye-slash",
    "fa-lock",
    "fa-unlock",
    "fa-shield",
    "fa-flag",
    "fa-flag-checkered",
    "fa-hourglass-half",
    "fa-praying-hands",
    "fa-cross",
    "fa-book-dead",
    "fa-fire",
    "fa-fire-alt",
    "fa-bolt",
    "fa-image",
    "fa-bell",
    "fa-comment",
    "fa-comments",
    "fa-star",
    "fa-compass",
    "fa-handshake",
    "fa-snowflake",
    "fa-sun",
    "fa-clock",
    "fa-hand-point-up",
    "fa-lightbulb",
    "fa-map",
    "fa-life-ring",
    "fa-gem",
    "fa-smile",
    "fa-surprise",
    "fa-sad-cry",
    "fa-meh",
    "fa-kiss-wink-heart",
    "fa-grin-stars",
    "fa-grin-hearts",
    "fa-frown",
    "fa-flushed",
    "fa-dizzy",
    "fa-angry",
    "fa-plane",
    "fa-car",
    "fa-rocket",
    "fa-ship",
    "fa-bicycle",
    "fa-key",
    "fa-tree",
    "fa-leaf",
    "fa-cloud",
    "fa-water",
    "fa-magnet",
    "fa-gears",
    "fa-flask",
    "fa-ticket",
    "fa-palette",
    "fa-feather",
    "fa-pen",
    "fa-anchor",
    "fa-atom",
    "fa-sign",
    "fa-question",
    "fa-wrench",
    "fa-hammer",
    "fa-robot",
    "fa-crown",
    "fa-box",
    "fa-chair",
    "fa-joint",
    "fa-ruler",
    "fa-scroll",
    "fa-coins",
    "fa-puzzle-piece",
    "fa-dice",
    "fa-glasses",
    "fa-shoe-prints",
    "fa-cookie-bite",
    "fa-wine-glass",
    "fa-wine-bottle",
    "fa-umbrella"
]))
